### ISSUE TITLE
Georgian Translation

### ISSUE THREAD

**Issue by Naviamold1** [SpotX-Official/SpotX#106]
### What language do you want to translate into?

Georgian

### Enter language name in PowerShell

ka

### 📝 Translation strings

```txt
Author          = "პაჩის ავტორი:"
Author2         = "@Amd64fox"
TranslationBy   = "თარგმანის ავტორი:"
TranslationBy2  = "@Naviamold1"
Incorrect       = "უპს, არასწორი შენატანი,"
Incorrect2      = "მაგრამ თავიდან სცადე"
Download        = "შეცდომა ჩაწერის დროს"
Download2       = "თავიდან ვცდი 5 წამში..."
Download3       = "შეცდომა ისევ"
Download4       = "შეამოწმეთ თქვენი კავშირი ქსელთან და თავიდან სცადე ინსტალაცია"
Download5       = "Spotify იწერება"
StopScrpit      = "სკრიპტი ჩერდება"
MsSpoti         = "Microsoft Store-ის ვერსია მოიძებნა რომელიც არ არის მხარდაჯერილი" 
MsSpoti2        = "წავშალოთ Spotify Microsoft Store-ის ვერსია [Y/N]"
MsSpoti3        = "ავტუმატურად იშლება Spotify MS..."
MsSpoti4        = "იშლება Spotify MS..."
Prem            = "მოდიფიკაცია პრემიუმ აკკოუნტის..."
OldV            = "მოიძებნა მოძველებული Spotify-ს ვერსია"
OldV2           = "თქვენი Spotify-ს {0} ვერსია არის მოძველებული, რეკომენდურია მისი აპგრეიდობა ამ ვერსიაზე {1}"
OldV3           = "გინდა განაახლოთ ? [Y/N]"
AutoUpd         = "აუტომატიკური აპდაიტი რეკომენდებულ ვერსიაზე"
DelOrOver       = "გინდა წაშალო ეხლანდელი ვერსია: {0} თუ თავიდან ჩაწერა? Y [წაშლა] / N [თავიდან ჩაწერა]"
DelOld          = "ძველი Spotify იშლება..."
NewV            = "არა მხარდაჯერილი Spotify-ს ვერსია არის მოწებნილი"
NewV2           = "თქვენი Spotify-ს {0} ვერსია ჯერ არ არის დატესტილი, ამჟამად არის სტაბილური {1} ვერსია"
NewV3           = "გინდათ რომ გააგრძელოთ {0} ვერსიაზე (შეცდომები შესაძლებელია) ? [Y/N]"
Recom           = "გინდათ რო ჩაიწეროთ რეკომენდირებული {0} ვერსია ? [Y/N]"
DelNew          = "იშლება არა ტესტირებულ Spotify..."
DownSpoti       = "ვტვირთავთ და ვიწერთ Spotify-ს"
DownSpoti2      = "გთხოვთ დაიცადოთ..."
PodcatsOff      = "პოდკასტები გათიშული"
PodcastsOn      = "პოდკასტები ჩართული"
PodcatsSelect   = "გინდათ რომ გათიშოთ პოდკასტები მთავარ გვერდიდან? [Y/N]"
DowngradeNote   = "რეკომენდირებული რომ დაბლოკოთ იმიტომ რომ იყო Spotify-ს დაქვეითება"
UpdBlock        = "Spotify-ს განახლებები დაბლოკილია"
UpdUnblock      = "Spotify-ს განახლებები არ არის დაბლოკილი"
UpdSelect       = "გინდათ რომ დაბლოკოთ Spotify-ს განახლებები? [Y/N]"
CacheOn         = "ქეშის გაწმენდა ჩართულია ({0})"
CacheOff        = "ქეშის გაწმენდა არ არის ჩართული"
CacheSelect     = "გინდათ რომ ჩართოთ ავტომატიკური ქეშის გაწმენდა? [Y/N]"
CacheDays       = "ქეში უფრო ძველია: XX დღეზე რომ იყოს გაწმენდილი "
CacheDays2      = "შეიყვანეთ the დღეების რაოდენობა 1-იდან 100-ამდე"
NoVariable      = "ცვლადი არ არის მოძებნილი"
NoVariable2     = "xpui.js -ში"
NoVariable3     = "licenses.html -ში"
NoVariable4     = "html =ში"
ModSpoti        = "Spotify იკერვება..."
Error           = "შეცდომა"
FileLocBroken   = "Spotify ფაილების ლოკაცია არის გადეხილი, წაშალეთ კლიენტი და თავიდან გაუშვით სკრიპტი"
Spicetify       = "Spicetify მოიზებნა"
NoRestore       = "SpotX უკვეა ჩაწერილი, მაგრამ ფაილები xpui.js.bak და xpui.css.bak აღსადგენად ვერ მოიძებნა. `nგთხოვთ წაშალეთ Spotify-ის აპლიკაცია და თავიდან გაუშვით Install.bat"
ExpSpotify      = "ექსპერიმენტული ფუნქციები, რომელსაც მართავს Spotify"
ExpStandart     = "ექსპერიმენტული ფუნქციები SpotX არ მოითავსება"
NoRestore2      = "SpotX უკვე დაინსტალირებულია, xpui.bak ვერ მოიძებნა. `nგთხოვთ, წაშალოთ Spotify აპლიკაცია და თავიდან გაუშვით Install.bat"
UpdateBlocked   = "Spotify-ს განახლებები უკვე დაბლოკერიბული არიან"
UpdateError     = "განახლებების დაბლოკვა ვერ მოხერხდა"
NoSpotifyExe    = "Spotify.exe ვერ მოიძებნა"
InstallComplete = "ინსტალაცია დასრულდა"
HostInfo        = "არასასურველი URL-ები ნაპოვნი მასპინძელის ფაილში"
HostBak         = "იქმნება hosts.bak-ის სარევეზნო ასლი..."
HostDel         = "ვცდილობთ რომ ამოვიღოთ არასასურველი URL-ები ორიგინალური მასპინძელის ფაილიდან..."
HostError       = "რაღაც შეცდომა მოხდა მასპინძელის ფაილის რედაქტირებისას, დაარედაქტირეთ ის ხელით ან გაუშვით სკრიპტი ადმინისტრატორის სახით"
```

**Comment by amd64fox** [comment]
Thanks
Please complete the translation of lines 1, 3 and 25

**Comment by Naviamold1** [comment]
Done!

**Comment by amd64fox** [comment]
Ok
Can you run the installation process to check if your translation is displayed correctly?

```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (iwr -useb 'https://raw.githubusercontent.com/amd64fox/Test/main/test.ps1').Content | iex
```

**Comment by Naviamold1** [comment]
Installation process is in English

**Comment by amd64fox** [comment]
This will only work if the Georgian language is set as the main language of the system.
What language is your default Windows OS?

**Comment by Naviamold1** [comment]
I changed this setting here to Georgian and it stayd in English, do you mean I have to set to Georgian when installing Windows?
![image](https://user-images.githubusercontent.com/89490126/183901078-a6045e0a-c4c0-45e5-bab2-60503cafb033.png)

**Comment by amd64fox** [comment]
Maybe.

You can force the installation of the patch in Georgian

try it
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/Test/main/test.ps1').Content) } -l ka"
```

**Comment by Naviamold1** [comment]
Unfortunately the language gets tagged out with symbols, but it looks like Microsoft is trying to add support for all languages but rn it doesnt work.
![image](https://user-images.githubusercontent.com/89490126/183907095-1a8ac66d-70c4-4ff9-811f-68363017bf34.png)

**Comment by amd64fox** [comment]
@dembeck 
Hello, do you have any idea how to make PowerShell terminal display Georgian language?

```ps1
$langStringsKA = @{
    
    Hi  = "გამარჯობა"
    Bye = "Ნახვამდის"
}

$langStringsKA
```
Works at ISE
![Снимок экрана 2022-08-11 133353](https://user-images.githubusercontent.com/62529699/184134543-09c5a775-6c98-43dd-992b-af8ac4381522.jpg)

does not work in terminal
![Снимок экрана 2022-08-11 133431](https://user-images.githubusercontent.com/62529699/184134552-bf2d0f21-c468-4b28-b43d-ed9fa504c62f.jpg)

**Comment by dembeck** [comment]
Since the language is installed on the system, it is likely an issue with the selected font in the console or the console encoding.


# Try First: Changing the Console Font

I would first try changing the console font. On Windows 11 the text showed correctly by default for me, but when I tested on Windows Server 2016 and 2019 I had to change the font to **SimSun-Ext8** though depending on your Windows version and installed fonts you might have other options. If one font does not work, try another.

To change the console font, in the console Window go to:
`Right Click the Title Bar -> Properties -> Font Tab`

### If changing the font does not work...

Please get and share the output of the following:

```powershell
$OutputEncoding
[System.Console]::OutputEncoding
[System.Console]::InputEncoding
```

# Try Next: Set the Profile Encoding

If changing the font did not work, changing the console encoding along with selecting a compatible font should fix the issue.

The easiest way to do this is to change the encoding of your PowerShell profile to utf8.

To save your profile with utf8 encoding run the following:
```powershell
Get-Content -Path $PROFILE -ErrorAction SilentlyContinue | Out-File -FilePath $PROFILE -Encoding utf8 -Force
```
This gets whatever is in your current PowerShell profile and saves it with utf8 encoding. If your profile is blank or does not exist, it just saves a blank profile with utf8 encoding. 

Then close and re-open PowerShell.

# Results

Please respond if just changing the font works, or if setting the profile encoding was also required to have the text show correctly. This information would be helpful in finding the correct solution for the script. 

I think that changing the console font is going to work. The console encoding, I assume would default to an encoding that is compatible with the Georgian language since it is installed on the system, and the console just picked an incompatible default font. My assumption might be wrong though, and so I look forward to finding out if you had to set the encoding too.

**Comment by amd64fox** [comment]
Thanks
For me it was enough to change the font to `SimSun-Ext8 `
But I have a different language on my system by default

I also found out that this problem can be solved just put [terminal windows
](https://docs.microsoft.com/en-us/windows/terminal/install)
@Naviamold1 As I understand it, you also do not have the Georgian language in the system by default?

**Comment by amd64fox** [comment]
Added language, if someone has problems write here
