### ISSUE TITLE
Spotify status not working properly in Discord

### ISSUE THREAD

**Issue by Veky121** [SpotX-Official/SpotX#119]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.92.647.ga4397eb7
- Windows: Windows 10 Pro OS | build 19044.1706
- PowerShell: 5.1.19041.1682
```

### 📝 Description

Iv recently moved from BlockTheSpot to SpotX bc i saw that you are working on new version with constant updates

After i updated,, my discord stop updating songs (song currently listening to), iv tryed removing connection with discord and adding it back with discord and it just worked for the current song i was listening to after the song finished it stopped working again

I have downloaded the uninstall spotify script you also made and install spotify again but still didnt work

i also tried to add Spicetify and it bricked your blocker and theyr web interface would not load (i first installed SpotX and then Spicetify)
then i ran install.bat and iv got this error
**SpotX has already been installed, but files to recover xpui.js.bak and xpui.css.bak not found. Please uninstall Spotify client and run Install.bat again**

but for SpotX blocking ads on spotify it works absolutely flawless 
hope you can solve this issues for me

**Comment by amd64fox** [comment]
SpotX can't affect Discord, problem is either in Discord or Spotify, it is not yet clear what exactly.

Reddit discussions at these links:
https://www.reddit.com/r/discordapp/comments/wsk2ap/discord_isnt_properly_displaying_current_spotify
https://www.reddit.com/r/discordapp/comments/wtc6ia/why_doesnt_my_discord_show_my_spotify_listening
https://www.reddit.com/r/discordapp/comments/wtch79/spotify_status_keeps_bugging

other answers to your questions are in the FAQ

**Comment by NekoSuneVR** [comment]
sorry report this but when install normal Spotify version as non modify it does work on Discord. so something SpotX is blocking it

i been manual adding AD blocker in it system then run full mode of .bat file and Discord and Spotify been working well

sec run SpotX it breaks Discord RPC or something wont send RPC request.

since Discord Pushes Request to Spotify Servers and Discord pulls it from there.

What SpotX thinks is Spotify is on Offline mode so no Server calls to Spotify server.

sometimes can be Cache issue with Spotify and Discord directly too, for my issue it was blocked
