### ISSUE TITLE
Files to recover xpui.js.bak and xpui.css.bak not found

### ISSUE THREAD

**Issue by eshaane** [SpotX-Official/SpotX#121]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.92.647.ga4397eb7
- Windows: Windows 11 Enterprise N 21H2
- PowerShell: 7.2.5
```

### 📝 Description

Just running the install at all, I have tried both PowerShell and the batch file but the same issue occurs.‌

The issue: After installing SpotX at the end it shows that the install failed even though the install went through.​​​‌​‌​​​​‌​​‌‌‌‌​​‌​‌​​‌‌​​​‌​​‌‌​​​‌‌‌​​​‌​‌​​‌‌​‌​‌‌​‌‌‌​

### 📸 Screenshots

![QByLLqMn](https://user-images.githubusercontent.com/62529699/186249634-7dfbb378-f704-451c-b736-6f46e45fe980.png)
‌​‌​​​‌​‌​​​​‌​​‌‌‌‌​​‌​‌​​‌‌​​​‌​​‌‌​​​‌‌‌​​​‌​‌​​‌‌​‌​‌‌​‌‌‌​

**Comment by amd64fox** [comment]
This error can only occur in two cases:

1. You installed SpotX first, then you installed Spicetify, and for some reason you installed SpotX again. In this case, it can't find the backup files since the first install was without Spicetify. Important, do not install SpotX first without Spicetify, and then with it, choose only one installation method and use only it.

1. Something or someone is deleting `xpui.js.bak` and `xpui.css.bak` backup files after installing SpotX.

In both cases, the problem is solved by a clean install. Of course, a clean installation is also needed for Spicetify without any restoration of past configurations.
