### ISSUE TITLE
DevTools on SpotX installation

### ISSUE THREAD

**Issue by ChickChuck2** [SpotX-Official/SpotX#143]
### Description of the new feature / enhancement

i was wondering if it would be a good idea to put the install devtools function in the modified client installation

**Comment by amd64fox** [comment]
It would be possible, but since version 1.1.80.699 access to devtools was limited. There is a workaround to enable devtools, but this can only be done for one client session and after a reboot everything will disappear. It is for this reason that I believe that it makes no sense to add developer tools to the spotx installation.

I have a [separate repository](https://github.com/amd64fox/Enable-devtools-Spotify) that activates devtools and its advanced settings, use it.
