### ISSUE TITLE
Spotify keep pausing randomly.

### ISSUE THREAD

**Issue by leoskinnertm** [SpotX-Official/SpotX#175]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

	United Kingdom

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.1.95.893.g6cf4d40c
- Windows: 10 21H2
- PowerShell: 5.1.19041.1682
```

### 📝 Description

1. I launch Spotify.
2. I play a song.
3. then the music pauses randomly.
4. and Spotify says it can't play the song right now.
5. I wait for some time and then it will play again.

**Comment by amd64fox** [comment]
Follow these 3 steps from the [FAQ](https://telegra.ph/SpotX-FAQ-09-19#I-have-a-bug-/-strange-client-behavior,-what-can-I-do-?)

**Comment by hallhoward221** [comment]
I have same problem. On official client and on SpotX on one of my windows 10. What kind of IPs in hosts can produce this bug? Because i have some IPs blocked there but no one with name "spotify" and etc.

**Comment by amd64fox** [comment]
First you need to check whether your hosts file is to blame or not, make a backup copy, and delete the original hosts file, restart your PC and then check your mistake again.

**Comment by hallhoward221** [comment]
> First you need to check whether your hosts file is to blame or not, make a backup copy, and delete the original hosts file, restart your PC and then check your mistake again.


Not hosts issue for me. With original hosts it was same. I've downgraded spotify to 1.1.69 and it works without that bug. I dont know what cause it

**Comment by amd64fox** [comment]
That is, you checked all versions from 1.1.95.893 to 1.1.69 ?

**Comment by hallhoward221** [comment]
> That is, you checked all versions from 1.1.95.893 to 1.1.69 ?

No, just downgraded to official 1.1.69

**Comment by hallhoward221** [comment]
PS it begins produce that bug after 1.90 version. I checked 1.90 and 1.86. 1.86 is working fine but 1.90 stucks again

**Comment by amd64fox** [comment]
`1.1.86` is now largely unsupported by SpotX unless using older releases or the `-bts` input parameter.

Apparently, this is a very rare error of the Spotify client, you can still use the downgraded version, you can also [create an error report here](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows), since perhaps the developers are not aware of this error.

**Comment by NeuroCPP** [comment]
one more thing to add it just didn't start to happen after 1.1.90 it was there even before that 
my suspicions are that this may happen due to reasons such as
1.Faulty Audio Driver 
2.You/your system may have unplugged and plugged the audio device such as your speakers which generally work on aux (ofc not all work on aux but this issue generally happens on aux based devices more)[bluetooth devices are also a cause,specially cheap and faulty ones]
3.Windows is IDIOT(likewise it might be same as reason 2) : sometimes audio service crashes and spotify(client) doesn't knows this and reports back that your device is unable to play song[and even if sound service is back again spotify still doesn't knows this] (if you change the song it will work again...i suppose? bcoz I have done that a LOT.)
[2012 issue](https://community.spotify.com/t5/Desktop-Windows/Can-t-play-current-track/m-p/10407#M39678) _this issue is quite old 😂 and they didn't have proper fix for that_
4.[maybe main issue](https://community.spotify.com/t5/Desktop-Windows/bug-Can-t-play-current-song-when-changing-audio-output/m-p/1536200#M27900)
**i didn't mention it previously but i also had the same issue that Spotify doesn't handle device output switching very well**
{PS: although this issue is closed I am adding it so people know}
