### ISSUE TITLE
BitDefender complaining after install

### ISSUE THREAD

**Issue by lorivaro** [SpotX-Official/SpotX#225]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Netherlands

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.99.878
- Windows: Windows 11 22H2 22621.819
- PowerShell: 5.1.22621.608
```

### 📝 Description

1. Turn off all applicable BitDefender protection buttons
2. Run the script as usual
3. Turn BitDefender back on
4. Run Spotify, it will work for a while
5. Later BitDefender will happily notify you that it disinfected a threat called "Spotify.exe"
6. Spotify is nowhere to be found and no longer works
...

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/64579257/203665749-e1f54cd2-1bc2-4a1f-b599-fd78fab3fcff.png)
![image](https://user-images.githubusercontent.com/64579257/203665207-be286547-0bdc-490f-b9f3-6202956ead42.png)

**Comment by lorivaro** [comment]
Yes, I have read https://github.com/SpotX-CLI/SpotX-Win/issues/134 but that covers the issue of false positives of the SpotX script itself, not Spotify.exe

**Comment by amd64fox** [comment]
And where is Spotx to blame?

Here are two tests with original `Spotify.exe` in virustotal

for [Spotify.exe](https://www.virustotal.com/gui/file/1ba204744afe70bba038a99872126a42866d75d2fc765c92c2b889ca4922d411) (1.1.99) and for [Spotify.exe](https://www.virustotal.com/gui/file/61bdc5372480c68ee4212e36432b3575e9a9a22488280e149188f55fa77fc5d0) (1.1.98)
99% that this is a false positive.
You can check it yourself on the source files of the original Spotify.

Therefore, wait until the base for your antivirus is updated or [send the source file](https://www.bitdefender.com/consumer/support/answer/29358/) to the laboratory yourself so that they fix this false positive even faster.

Also, until this problem is solved, you can add the Spotify.exe file to the exceptions so that it does not delete it every time.

**Comment by lorivaro** [comment]
Thanks for the quick response. To be clear, I'm very pleased with SpotX and I completely agree this is a false positive. Just had this issue come up recently so I thought I should bring it up here. Yeah for the time being I could add Spotify as an exception, or just use the original unpatched version, which seems to work fine, for the rest of my Premium trial.
