### ISSUE TITLE
Song/Podcast skipping when clicking/sliding the progress bar in the desktop app

### ISSUE THREAD

**Issue by nijiyamaharjan** [SpotX-Official/SpotX#227]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Nepal

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.1.99.8578.g1e4ccc6e
- Windows: Windows 11 21H2 22621.819
- PowerShell: 5.1.22621.608
```

### 📝 Description

1. Play any song.
2. Try to slide the playing bar left or right.
3. It immediately skips to the next song.
...

**Comment by amd64fox** [comment]
Original Spotify client bug, it looks like this issue is already known to the developers, wait for the status update [here](https://community.spotify.com/t5/Ongoing-Issues/Song-Podcast-skipping-when-clicking-sliding-the-progress-bar-in/idi-p/5461014)
or try to roll back to older versions of the client using [this instruction](https://github.com/amd64fox/Rollback-Spotify)

**Upd:**
In the meantime, you can try out the following workaround:

1. Go to Settings > Audio quality and set the Streaming quality to High.

2. Scroll all the way down to Compatibility and disable hardware acceleration.
