### ISSUE TITLE
Volume slider doesn't work on podcasts with video

### ISSUE THREAD

**Issue by Ali229** [SpotX-Official/SpotX#270]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

USA

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.2.582.gfae9c59b
- Windows: 11 22H2
- PowerShell: 5.1.22621.963
```

### 📝 Description

I've recently updated SpotX and noticed that the volume slider does nothing while playing any podcasts that have video, the slider does work during songs & other podcasts I've tried. Let me know if I can provide any other information.

I tried:
1. Running the uninstall bat file and reinstalled SpotX
2. At least two video podcasts (Joe Rogan & Misfits podcast) have this issue
3. Tried closing the video and listening to the audio only, issue persists

**Comment by amd64fox** [comment]
Yep, I checked, this bug is reproduced in the original Spotify (1.2.2.582).
Please submit a bug report [here](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows), also if you are annoyed by this bug at the moment then downgrade your version to [1.2.1.968](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=0) or lower, also don't forget to block updates during installation SpotX.
