### ISSUE TITLE
Need update integration

### ISSUE THREAD

**Issue by zakblacki** [SpotX-Official/SpotX#337]
### Description of the new feature / enhancement

It would be nice if we could have option to update/upgrade without having to check in here or reinstall  
something similar just like `spicetify upgrade` prompt 

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
Today there are no plans to compile the SpotX code as it is implemented in Spicetify, since using the powershell and bash script is more convenient from development to running the script on a PC.

For a more convenient launch, you can create your own bat file or powershell string ([read more here](https://github.com/amd64fox/SpotX/discussions/60)), you can save it to your PC and use it for future installations/updates of SpotX.

Also, if your level of programming allows, then you can create any kind of installation that is convenient for you, for example, I recently came across such a [SpotX installer](https://github.com/SirDank/dank.tool#-spotx--spicetify-installer-).

If SpotX grows into something more in the future, then perhaps we will revise the installation/update scheme
