### ISSUE TITLE
Yesterday, I installed it and Spotify banned my account.

### ISSUE THREAD

**Issue by pablotorres90** [SpotX-Official/SpotX#349]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Mexico

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 
- Windows: 
- PowerShell:
```

### 📝 Description

1.
2.
3.
...

**Comment by amd64fox** [comment]
for the use of SpotX there was not a single ban in the entire history of its existence

in 99 cases out of 100 Spotify bans accounts due to downloading music by recording an audio stream directly from the client, the remaining 1% are rare cases of abuse of their API

Please read the FAQ before creating useless issues.

**Comment by 4m1n** [comment]
same here. a few weeks ago my account was banned. I can't think of any reason other than SpotX. must be a new enforcement by Spotify because I've been using SpotX for over a year without any problem.
