### ISSUE TITLE
Spotify seems offline but it can play song

### ISSUE THREAD

**Issue by SupLiCatinG** [SpotX-Official/SpotX#459]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Turkey

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 
Spotify für Windows (32 bit)
1.2.13.661.ga588f749
Spicetify v2.20.3
- Windows: 22H2 W10 19045.3154
- PowerShell: 5.1.19041.3031
```

### 📝 Description

I had this same problem back in the October (https://github.com/amd64fox/SpotX/issues/197)
I cant scrobble, discord spotify status seems not working and i cant select computer in spotify connect. 
I used the usual old theme automatic installer ([Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -v 1.2.13.661.ga588f749-4064 -confirm_spoti_recomended_over -block_update_on")

**Comment by amd64fox** [comment]
This issue is not related to SpotX. Completely uninstall the current Spotify and install the [latest version](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=0). If the problem persists, contact [Spotify support](https://community.spotify.com/t5/Desktop-Windows/bd-p/desktop_windows).
