### ISSUE TITLE
Enhanced songs in your liked playlist wont play

### ISSUE THREAD

**Issue by ghost** [SpotX-Official/SpotX#48]
Spotify Version: 1.1.86.857.g3751ee08
Plan Spotify: Free
Windows Version: Windows 10 21H2, OS build 19044.1288
PowerShell Version:  5.1.19041.1237
1. Clicking the enhance playlist button correctly adds multiple new songs to your liked songs playlist.
2. However, When attempting to play the song your met with a blank bar, play button being grayed out
3. The added songs will be skipped by the queue automatically
![WontPlay](https://user-images.githubusercontent.com/45320697/170803903-99495ac4-0930-4391-8d3a-ca8f6a74bd55.PNG)

**Comment by amd64fox** [comment]
Hello, thanks for the feedback, this is not a bug of the mod, this is a new experimental feature, Spotify only added it, but did not activate it due to the fact that it has not yet been finalized.
It may take a few days or weeks for `1.1.86.857` to work, or you may need to wait for a new version of the client.
