### ISSUE TITLE
Spotify crashes on startup

### ISSUE THREAD

**Issue by TheDomoKun** [SpotX-Official/SpotX#581]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Russia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify:  1.2.35.663
- Windows: Windows 11 Pro 22621
- PowerShell:  5.1.22621.2428
```

### 📝 Description

1. Deleted the old spotify using the utility from the readme
2. Installed spotX (I tried all versions)
3. Spotify crashes on startup with error code: 0xc0000022
...

**Comment by amd64fox** [comment]
at what point do you get this error (show a screenshot)

also, your region cannot be Russian, since Spotify is not officially present in Russia

**Comment by TheDomoKun** [comment]
Spotify crashes when the window has not yet been created
![изображение](https://github.com/SpotX-Official/SpotX/assets/34937532/f5fb0058-d0a0-4d3e-ba16-e86a03fdba44)

**Comment by TheDomoKun** [comment]
after clicking OK a gray window appears and the error occurs again

**Comment by TheDomoKun** [comment]
This also happens with already patched Spotify builds from Telegram

**Comment by amd64fox** [comment]
more like a Windows environment error, completely uninstall the current client, install the [original Spotify](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=0) and try again

**Comment by TheDomoKun** [comment]
I installed the original one and logged into my account, everything worked, then I patched it and it stopped launching

**Comment by TheDomoKun** [comment]
after that it started

**Comment by amd64fox** [comment]
> after that it started

what started?

> as I understand it you need before/after files?

at this stage I did not ask for files, you just need to replace the files and launch the client as I showed in the instructions above

**Comment by TheDomoKun** [comment]
Spotify started to launch after I renamed .bak to .exe

**Comment by amd64fox** [comment]
now that it turns out that the problem is with the patched Spotify.exe, you need to send it here, reinstall the latest Spotify, install SpotX again, make sure that the error still appears, go to the `AppData\Roaming\Spotify` folder and send the Spotify.exe file here

**Comment by TheDomoKun** [comment]
https://file.io/rAuahXoR9JZz

**Comment by amd64fox** [comment]
you sent a 64 bit exe

I checked it and did not find any visible problems, this exe also starts successfully in my test virtual machine on the official Windows 11 Pro x64, version 23h2 updated March 2024

so if you actually did a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) from the faq and it didn't help then I'm guessing the problem is in your windows build

on the other hand, you say that the original Spotify is working fine for you, but the error that you receive has little to do with Spotify, it is precisely a failure in one of the parts of the registry related to Windows accounts and security, in general there is still a lot of strange things, if indeed the problem is with patches, then there should be more people with a similar problem, let's wait ..

**Comment by amd64fox** [comment]
Closed, as the issue did not receive confirmation.
