### ISSUE TITLE
Spotify destination broken

### ISSUE THREAD

**Issue by LynicTaken** [SpotX-Official/SpotX#625]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Turkey

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: 1.2.45.454.gc16ec9f6
- Windows: Windows 10 Pro 22H2
- PowerShell: 5.1.19041.4842
```

### 📝 Description

1.Spotify makes auto update
2.Try to install Spotx
3.Got this error
Everytime when Spotify gets update itself i need to reinstall SpotX. Thats normal but everytime i get this error. How i fix it? Uninstall Spotify completely with [Uninstall Spotify](https://github.com/amd64fox/Uninstall-Spotify), reinstall again and than reinstall SpotX.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/498b74be-dcbd-42ec-a52c-7bfee143872e)

**Comment by amd64fox** [comment]
as the error message says your client files location is broken, probably because you install spicetify or something else before spotx, a [clean install](https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation) usually solves the problem.

Also, don't forget to block Spotify automatic updates while installing spotx to avoid overwriting spotx in the future
