### ISSUE TITLE
"Filter tags on the liked songs" not working

### ISSUE THREAD

**Issue by occasionalbughunter** [SpotX-Official/SpotX#633]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

### Сountry of your account

Poland

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: 1.2.46.462.gf57913e0
- Windows: 10 - 19045.4894
- PowerShell: 5.1.19041.4894
```

### 📝 Description

1. Install latest spotify using Install_New_theme.bat
2. Check favourites songs list.
3. Observe that there is no filter (hence "Filter tags on the liked songs" feature is not working).

### 📸 Screenshots

![obraz](https://github.com/user-attachments/assets/46100ab5-460c-4012-9421-026b815ad472)

**Comment by amd64fox** [comment]
1. perform a clean installation from the FAQ.
2. log into the client and wait for it to fully load (the time for the client to fully load depends on your internet connection and PC performance).
3. go to the likes page, if there are no tags yet, try waiting and periodically switching the likes page to another playlist and back.

btw file `Install_New_theme.bat` is not intended for premium accounts.

**Comment by occasionalbughunter** [comment]
I reinstalled spotify again but it did not help. Tried downgrading to 1.2.45 (old UI) but it did not help too.
Do you think I should try different installer parameters for premium account?
It was free when I initially installed it few months ago, but now I am at premium. 
Feature newer worked for me, but I decided to finally report it now. 
Not sure what these tags are, am I supposed to add them manually? Maybe this is the problem because I've never done it, but I suppose they are automatically added to songs like on steam?

**Comment by amd64fox** [comment]
![Снимок экрана 2024-09-22 234155](https://github.com/user-attachments/assets/8dcab6f7-ae56-48ce-9bc1-ced17c4f3833)


The tags bar only appears on the liked songs page. Spotx applies this patch for everyone users without parameters, supported versions are 1.2.29 - 1.2.46+.


If the actions I mentioned above did not help, then the problem lies with your account or an issue between your network and Spotify servers, neither of these problems is related to Spotx.

if you want i can log into your account and check the tag panel on my pc, write to us in the telegram group if necessary
