### ISSUE TITLE
enable carousel on homepage

### ISSUE THREAD

**Issue by cisko99za** [SpotX-Official/SpotX#664]
### 🧐 Have you read the FAQ and viewed similar issues?

- [X] I have read the FAQ
- [X] I have checked older issues, open and closed
- [X] I did a clean install of SpotX as <a href="https://telegra.ph/SpotX-FAQ-09-19#1.-Clean-installation">described in the FAQ</a>

Spotify Plan? Free

Spicetify installed? No

### ℹ Computer information

```markdown
- Spotify: latest 1.2.53.438 x64
- Windows: 11 x64 24H2
- PowerShell: 7.4.1
```

### 📝 Description

if i remember correctly the official version has a > symbol to scroll through the various playlists in the same field, which i don't see in SpotX. example: in Made for you i only see Daily Mix 1-3-4-6. to see all the playlists i need to click on Show all. I seem to remember that in previous versions there was a > symbol to scroll through the playlists to the right, displaying them all

edit: confirmed. from official version have arrow to show from right side all playlist available (not on Made for you but from others playlist)

### 📸 Screenshots

![shot_01](https://github.com/user-attachments/assets/3267a8b3-68c8-43dd-86d8-cfb57f4cc848)

**Comment by amd64fox** [comment]
The exp that enabled the carousel on the homepage was disabled due to [slowdowns on the homepage and homemenu](https://github.com/SpotX-Official/SpotX/issues/624). I just checked it in the new versions, and nothing has changed.

If you need this exp, you can enable it yourself using [this](https://github.com/SpotX-Official/SpotX/discussions/47), name of the exp: `enableHomeCarousels`

**Comment by cisko99za** [comment]
wonderful. thanks
