### ISSUE TITLE
Improving UX when installation completed

### ISSUE THREAD

**Issue by asedii** [SpotX-Official/SpotX#73]
## 📝 Description of the idea

1. Open Spotify after installation completed
2. Use pause before the exit (maybe it's better not to use the exit command!?)

I ran the usual installation command in Powershell and suddenly the Powershell window closed because it was minimized i didn't know whether the installation was successful or not.

**Comment by amd64fox** [comment]
In order for the client to start immediately after the installation is completed, add the incoming parameter `-start_spoti` to the powershell command
```ps1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex "& { $((iwr -useb 'https://raw.githubusercontent.com/amd64fox/SpotX/main/Install.ps1').Content) } -start_spoti"
```
You can study the full list of parameters [here](https://github.com/amd64fox/SpotX/discussions/60) in order to create your own more flexible installer.

And about the automatic closing of the poweshell window, yes, you are absolutely right, I don’t know why I left this "exit" there
Thanks for the feedback
fixed
