### ISSUE TITLE
The ability to like a song coming from Local Files (Liking Local Files Songs)

### ISSUE THREAD

**Issue by JustaRandomUser12** [SpotX-Official/SpotX#87]
I've been using Spotify for quite a while now, and I've always wanted the ability to like "Local Files" songs, but I've never been able to. I'm just wondering if that feature could possibly be added?

I added an example of what I mean in Screenshots.

## 📷 Screenshots

![Example](https://user-images.githubusercontent.com/87282309/180486121-437ba06a-bfb5-4a6a-9958-e1d488427cb8.png)

**Comment by amd64fox** [comment]
Unfortunately, Spotify has removed this feature from the desktop app.

But there is a way that uses the mobile app to like local files.

1. Have both the desktop app and the mobile app running and connected to the same local network (so that when you play a song on the desktop app, the song playing show up on the mobile app).

1. Start playing the local file song on the desktop app.

1. Click on the heart to like the currently playing local file song on the mobile app.

1. Your local file should now appear in the `liked songs` in the desktop app.
